dist: 5000
seed: 413666

test: 
  chrom: "chr1"
  start: 0
  end: 249250621
  window_size: 200

tuning: 
  chrom: "chr2"

training_data_size: 100000
tuning_data_size: 10000
num_trees: 100
random_search_n: 50

paths:
  working_dir: "/u/home/s/skwon94/project-ernst/skwon94/pairwise/"
  chrom_size_file: "/u/home/s/skwon94/project-ernst/skwon94/pairwise/hg19.chrom.sizes"
  output_dir: "/u/home/s/skwon94/project-ernst/skwon94/pairwise/model/dist5000"
  feature:
    dnase_chipseq_input_dir: "/u/home/s/skwon94/project-ernst/skwon94/aligned_model/feature/preprocessed/hg19_DNaseChIPseq"
    chromhmm_input_dir: "/u/home/s/skwon94/project-ernst/skwon94/aligned_model/feature/preprocessed/hg19_ChromHMM"
  binary_bed_annot_dir: "/u/home/s/skwon94/project-ernst/skwon94/aligned_model/validation/bed_files/binary"